@startuml
!include <C4/C4_Container>
Person(user, "User")
Person(admin, "Content manager")
System(front, "Web Application", "Frontend")
System_Boundary(movie, "Movie Service") {
    Container(movie_api, "Movie API", "Python, FastAPI")
    ContainerDb(movie_db, "DB", "ElasticSearch")
}
System_Ext(oauth, "OAuth Provider")
System_Boundary(auth, "Auth Service") {
    Container(auth_api, "Auth API", "Python, Flask")
    ContainerDb(auth_db, "Auth DB", "PostgreSQL")
}
System_Boundary(content, "Content administration") {
    Container(content_panel, "Content admin panel", "Python, Django")
    ContainerDb(content_db, "DB", "PostgreSQL")
}
System_Boundary(ugc, "UGC Service") {
    ContainerDb(kafka, "kafka", "Kafka")
    ContainerDb(clickhouse, "Storage", "ClickHouse")
}
Rel(user, front, "Uses", "HTTPS")
Rel(admin, content_panel, "Uses", "HTTPS")
Rel(front, movie_api, "Uses")
Rel_R(front, auth_api, "Uses")
Rel_R(auth_api, auth_db, "Uses")
Rel_R(auth_api, oauth, "Uses")
Rel_R(movie_api, movie_db, "Uses")
Rel_R(movie_api, kafka, "Send")
Rel_R(kafka, clickhouse, "ETL")
Rel_L(content_panel, content_db, "Uses")
Rel(content_db, movie_db, "ETL")
@enduml