FROM python:3.9.9-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get -y update && apt-get install -y ffmpeg
RUN apt install -y netcat

RUN pip install --upgrade pip
COPY ./requirements/*.txt ./
RUN pip install -r dev.txt

COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.dev.sh
RUN chmod +x /usr/src/app/entrypoint.dev.sh

COPY ./src .

ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]

CMD ["python", "main.py"]